[tool.black]
    line-length = 99
    target-version = ["py38"]
    include = '\.py$'
    exclude = '''
    /(
          \.eggs
        | \.git
        | \.vscode
        | \.hg
        | \.mypy_cache
        | \.tox
        | \.venv
        | _build
        | buck-out
        | build
        | dist
    )/
    '''

[tool.isort]
    profile = "black"
    line_length = 99
    atomic = true
    src_paths = ["isort", "test"]
    multi_line_output = 7
    order_by_type = true
    sections = ["FUTURE","STDLIB","FIRSTPARTY","THIRDPARTY","LOCALFOLDER"]
    known_third_party = ["flask", "werkzeug"]
    known_first_party = [
        "reddash",
    ]
    skip = [".gitignore"]
    skip_glob = [".github/*", ".git/*", ".vscode/*", "docs/*"]